version: "3"

services:
  app:
    build:
      context: .
    volumes:
      - ./bookshelf:/bookshelf/bookshelf
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env.dev
  db:
    image: postgres:11.5-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
  